# Generated by Django 4.2.6 on 2023-11-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_license_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
