# Generated by Django 4.2.6 on 2023-11-17 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_business_nit_business_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('destination_table', models.CharField(max_length=100)),
                ('selected_sheet', models.CharField(max_length=50)),
                ('headers_index', models.IntegerField()),
                ('columns_mapping', models.JSONField()),
                (
                    'related_model',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')
                ),
            ],
        ),
    ]
