# Generated by Django 4.2.6 on 2023-10-17 05:34

from typing import List

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("phone1", models.CharField(blank=True, max_length=15, null=True)),
                ("business", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Valuation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField()),
                ("tools", models.IntegerField(default=None, null=True)),
                ("standars", models.IntegerField(default=None, null=True)),
                ("avaliability", models.IntegerField(default=None, null=True)),
                ("level", models.IntegerField(default=None, null=True)),
                ("management", models.IntegerField(default=None, null=True)),
                ("business", models.CharField(max_length=255)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="customers.customer")),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="customers.customer")),
            ],
        ),
    ]
