# Generated by Django 4.2.6 on 2023-10-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
