# Generated by Django 4.2.6 on 2023-11-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_endcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endcustomer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='endcustomer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='endcustomer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='endcustomer',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='endcustomer',
            name='customer_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código del cliente'),
        ),
        migrations.AlterField(
            model_name='endcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='endcustomer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='endcustomer',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='endcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Télefono de contacto'),
        ),
    ]
