# Generated by Django 4.2.6 on 2023-11-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_endcustomer_address_alter_endcustomer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endcustomer',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellidos'),
        ),
    ]
