# Generated by Django 4.2.6 on 2023-11-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_endcustomer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endcustomer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='endcustomer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='endcustomer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='endcustomer',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombres'),
        ),
    ]
