# Generated by Django 4.2.6 on 2023-11-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_employee_last_name_alter_employee_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='business',
        ),
    ]
