# Generated by Django 4.2.6 on 2023-11-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_cost_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Costo del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código del producto'),
        ),
    ]
