# Generated by Django 4.2.6 on 2023-11-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_cost_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='gruop_inventory',
            field=models.TextField(null=True, verbose_name='Grupo de inventario'),
        ),
        migrations.AddField(
            model_name='product',
            name='line',
            field=models.TextField(null=True, verbose_name='Linea'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_inventory',
            field=models.TextField(null=True, verbose_name='Tipo de inventario'),
        ),
    ]
