# Generated by Django 4.2.6 on 2023-10-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_creditnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
