# Generated by Django 4.2.6 on 2023-11-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_amount_alter_sale_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
