# Generated by Django 4.2.6 on 2023-11-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
