# Generated by Django 4.2.6 on 2023-11-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_sale_amount_alter_sale_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='discount',
            new_name='discount_value',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='product_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='amount',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='final_value',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_successful',
        ),
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(max_length=50, null=True, verbose_name='Canal de la transacción'),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Código del vendedor'),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name='Identificador de la transacción'
            ),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Tipo de transacción'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
        migrations.DeleteModel(name='CreditNote',),
    ]
